# Generated by Django 2.2.1 on 2019-06-05 16:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_user_subscribed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribetransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscribetransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
