# Generated by Django 2.2.1 on 2019-07-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20190606_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscribed_date',
            field=models.DateTimeField(null=True),
        ),
    ]
