# Generated by Django 2.2.1 on 2019-06-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_remove_user_friends_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
