# Generated by Django 2.2.1 on 2019-06-11 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20190611_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='url',
        ),
    ]
