# Generated by Django 2.2.1 on 2019-06-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_remove_train_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='is_trained',
            field=models.BooleanField(default=False),
        ),
    ]
