# Generated by Django 2.2.1 on 2019-05-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20190522_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
