# Generated by Django 2.2.1 on 2019-06-18 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_trainmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train',
            old_name='train_class',
            new_name='label',
        ),
    ]
