# Generated by Django 2.2.1 on 2019-05-23 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_user_photo_in_use'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floorplan',
            old_name='shape_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='floorplan',
            old_name='snapshot',
            new_name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='floorplan',
            name='is_image_type',
        ),
        migrations.RemoveField(
            model_name='floorplan',
            name='shapes',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='floorplan',
            name='tags',
            field=models.CharField(default='game', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='floorplan',
            index=models.Index(fields=['-updated_at'], name='floor_plans_updated_7c142d_idx'),
        ),
    ]
