# Generated by Django 2.2.1 on 2019-05-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='ar_mark_image',
            field=models.CharField(default='Ar-mark-image', max_length=150),
            preserve_default=False,
        ),
    ]
