# Generated by Django 2.2.1 on 2019-06-25 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_auto_20190625_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainimage',
            name='embedding',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
