# Generated by Django 2.2.1 on 2019-06-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_trainimage_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainimage',
            name='embedding',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='trainmodel',
            name='embedding',
            field=models.CharField(max_length=350),
        ),
    ]
