# Generated by Django 2.2.1 on 2019-05-25 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_auto_20190525_2156'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
