# Generated by Django 2.2.1 on 2019-06-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_auto_20190626_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainimage',
            name='embedding',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='trainmodel',
            name='embedding',
            field=models.TextField(max_length=1000),
        ),
    ]
