# Generated by Django 2.2.1 on 2019-05-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='plan_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='plan',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.TextField(default='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='icon',
            field=models.CharField(default='icon', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='sub_name',
            field=models.CharField(default='sub_name', max_length=100),
            preserve_default=False,
        ),
    ]
