# Generated by Django 2.2.1 on 2019-05-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_auto_20190526_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(default='description'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='sub_name',
            field=models.CharField(default='sub_name', max_length=100),
        ),
    ]
