# Generated by Django 2.2.1 on 2019-05-27 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_auto_20190527_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscribed_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='backend.Plan'),
        ),
    ]
