# Generated by Django 2.2.1 on 2019-05-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_auto_20190527_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribetransaction',
            name='plan_price',
            field=models.FloatField(null=True),
        ),
    ]
