# Generated by Django 2.2.1 on 2019-05-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_auto_20190527_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribetransaction',
            name='subscription_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
