# Generated by Django 2.2.1 on 2019-05-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_auto_20190527_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='ar_mark_image',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
