# Generated by Django 2.2 on 2019-05-17 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20190517_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tests',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
