# Generated by Django 2.2 on 2019-05-17 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_user_tests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tests',
        ),
    ]
