# Generated by Django 2.2.1 on 2019-05-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20190518_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number_verified',
            field=models.BooleanField(default=False),
        ),
    ]
