# Generated by Django 2.2.1 on 2019-05-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_in_use',
            field=models.IntegerField(default=20),
        ),
    ]
