# Generated by Django 2.2.1 on 2019-05-23 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20190524_0155'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
